spring:
  datasource:
    url: ${PM_DB_URL:jdbc:postgresql://localhost:5432/pricemonitordb}
    username: ${PM_DB_USERNAME:user}
    password: ${PM_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: ${PM_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  flyway:
    enabled: false
  data:
    redis:
      host: ${PM_REDIS_HOST:localhost}
      port: ${PM_REDIS_PORT:6379}
      password: ${PM_REDIS_PASSWORD:}
  docker:
    compose:
      enabled: ${PM_COMPOSE_ENABLED:true}

logging:
  level:
    org.apache.kafka: WARN
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.github.pricemonitor: DEBUG

app:
  jwt:
    secret: ${PM_JWT_SECRET:404E635266556A586E3272347538782Q423F4428472B4X6290645367566B5970}
  client-url: ${PM_CLIENT_URL:http://localhost:4200}
