spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricemonitordb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  redis:
    host: localhost
    port: 6379
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 02400b3988dc9f
    password: abe6d2f787a614
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.apache.kafka: WARN
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: 404E635266556A586E3272347538782Q423F4428472B4X6290645367566B5970
    verification-expiration-ms: 10800000
    access-expiration-ms: 1800000
    refresh-expiration-ms: 2592000000
  server-url: http://localhost:8080
  client-url: http://localhost:4200
  api:
    verification-path: /api/v1/auth/verify?token=
    reset-password-path: /api/v1/auth/reset-password?token=
  agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0