CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       _created TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                       public_id UUID NOT NULL,
                       username VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       verified BOOLEAN NOT NULL,
                       email_alerts_enabled BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX idx_users_email
    ON users (email);

CREATE UNIQUE INDEX idx_users_username
    ON users (username);

CREATE UNIQUE INDEX idx_users_public_id
    ON users (public_id);


CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          _created TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          product_url VARCHAR(1000) NOT NULL,
                          image_url VARCHAR(1000),
                          current_price NUMERIC(19, 2) NOT NULL,
                          currency VARCHAR(3),
                          last_updated TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                          shop VARCHAR(255),
                          favicon_url VARCHAR(1000),
                          available BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX idx_product_url
    ON products (product_url);


CREATE TABLE price_alerts (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              _created TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                              public_id UUID NOT NULL,
                              user_id BIGINT NOT NULL,
                              product_id BIGINT NOT NULL,
                              target_price NUMERIC(19, 2) NOT NULL,
                              active BOOLEAN NOT NULL,

                              CONSTRAINT fk_price_alerts_user
                                  FOREIGN KEY (user_id)
                                      REFERENCES users (id),

                              CONSTRAINT fk_price_alerts_product
                                  FOREIGN KEY (product_id)
                                      REFERENCES products (id)
                                      ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_price_alerts_public_id
    ON price_alerts (public_id);


CREATE TABLE price_history (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               _created TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                               recorded_price NUMERIC(19, 2) NOT NULL,
                               product_id BIGINT NOT NULL,

                               CONSTRAINT fk_price_history_product
                                   FOREIGN KEY (product_id)
                                       REFERENCES products (id)
                                       ON DELETE CASCADE
);


CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               _created TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                               public_id UUID NOT NULL,
                               user_id BIGINT NOT NULL,
                               product_id BIGINT,
                               product_name VARCHAR(255),
                               type VARCHAR(255) NOT NULL,
                               read BOOLEAN NOT NULL,
                               trigger_price NUMERIC(19, 2),

                               CONSTRAINT fk_notifications_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES users (id),

                               CONSTRAINT fk_notifications_product
                                   FOREIGN KEY (product_id)
                                       REFERENCES products (id)
);

CREATE UNIQUE INDEX idx_notifications_public_id
    ON notifications (public_id);

CREATE INDEX idx_notifications_user_id
    ON notifications (user_id);